# Copyright (c) 2018-2023, NVIDIA CORPORATION.

{% set py_version = environ['CONDA_PY'] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

{% set data = load_file_data("../../../pyproject.toml", from_recipe_dir=True) %}

package:
  name: pynvjitlink
  version: {{ data.get("project", {}).get("version", "") }}

source:
  path: ../../..

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake >=3.26.4
    - sysroot_{{ target_platform }} 2.17
    - cuda-version ={{ cuda_version }}
  host:
    # We get libnvjitlink from the host's RPM packages, which are updated
    # sooner than conda sources.
    #- libnvjitlink-dev
    #- libnvjitlink-static
    - cuda-version ={{ cuda_version }}
    - python
    - pip
    - scikit-build-core
  run:
    - python
    - numba >=0.57
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}

test:
  imports:
    - pynvjitlink
  source_files:
    - pynvjitlink/tests/test_nvjitlink_api.py
    - pynvjitlink/tests/test_nvjitlink.py
    # Extra files for testing edge cases of libnvjitlink
    # see test_nvjitlink_api.py for details
    - pynvjitlink/tests/test_device_functions.cubin
    - pynvjitlink/tests/test_device_functions.fatbin
    - pynvjitlink/tests/undefined_extern.cubin
  requires:
    - pytest
  commands:
    - pytest -v

about:
  home: https://rapids.ai/
  dev_url: https://github.com/rapidsai/pynvjitlink
  doc_url: https://github.com/rapidsai/pynvjitlink/blob/main/README.md
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  license_url: https://github.com/rapidsai/pynvjitlink/blob/main/LICENSE
  summary: nvJitLink Python binding
