# Copyright (c) 2018-2024, NVIDIA CORPORATION.

{% set data = load_file_data("pyproject.toml") %}

package:
  name: pynvjitlink
  version: {{ data.get("project", {}).get("version", "") }}

source:
  path: ../../..

build:
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cuda-version {{ cuda_version }}
    - cmake >=3.26.4
    - ninja
    - sysroot_{{ target_platform }} 2.17
  host:
    - libnvjitlink-dev
    - libnvjitlink-static
    - cuda-version {{ cuda_version }}
    - python
    - pip
    - scikit-build-core
  run:
    - python
    - numba >=0.57
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}

#test:
#  #imports:
#  #  - pynvjitlink
#  source_files:
#    - pynvjitlink/tests/test_patch.py
#    - pynvjitlink/tests/test_pynvjitlink.py
#    - pynvjitlink/tests/test_pynvjitlink_api.py
#    - test_binary_generation/*
#  requires:
#    - {{ compiler('c') }}
#    - {{ compiler('cxx') }}
#    - {{ compiler('cuda') }}
#    - cuda-version ={{ cuda_version }}
#    - make
#    - pytest
#  commands:
#    - pushd test_binary_generation && make && popd
#    - pytest -v

about:
  home: https://rapids.ai/
  dev_url: https://github.com/rapidsai/pynvjitlink
  doc_url: https://github.com/rapidsai/pynvjitlink/blob/main/README.md
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  license_url: https://github.com/rapidsai/pynvjitlink/blob/main/LICENSE
  summary: nvJitLink Python binding
